kind: pipeline
type: docker
name: feature-calendar

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd calendar
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-calendar

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_CALENDAR_STAGING
      tags: latest
      dockerfile: calendar/Dockerfile
      context: calendar
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_CALENDAR_STAGING:
        from_secret: DOCKER_REPO_CALENDAR_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_CALENDAR_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_CALENDAR_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-calendar

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_CALENDAR
      tags: latest
      dockerfile: calendar/Dockerfile
      context: calendar
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_CALENDAR:
        from_secret: DOCKER_REPO_CALENDAR
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_CALENDAR, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_CALENDAR
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push

---
kind: pipeline
type: docker
name: feature-dashboard

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd dashboard
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-dashboard

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_DASHBOARD_STAGING
      tags: latest
      dockerfile: dashboard/Dockerfile
      context: dashboard
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_DASHBOARD_STAGING:
        from_secret: DOCKER_REPO_DASHBOARD_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_DASHBOARD_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_DASHBOARD_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-dashboard

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_DASHBOARD
      tags: latest
      dockerfile: dashboard/Dockerfile
      context: dashboard
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_DASHBOARD:
        from_secret: DOCKER_REPO_DASHBOARD
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_DASHBOARD, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_DASHBOARD
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push


---
kind: pipeline
type: docker
name: feature-chat

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd chat
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-chat

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_CHAT_STAGING
      tags: latest
      dockerfile: chat/Dockerfile
      context: chat
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_CHAT_STAGING:
        from_secret: DOCKER_REPO_CHAT_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_CHAT_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_CHAT_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-chat

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_CHAT
      tags: latest
      dockerfile: chat/Dockerfile
      context: chat
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_CHAT:
        from_secret: DOCKER_REPO_CHAT
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_CHAT, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_CHAT
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push
---
kind: pipeline
type: docker
name: feature-discussion

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd discussion
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-discussion

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_DISCUSSION_STAGING
      tags: latest
      dockerfile: discussion/Dockerfile
      context: discussion
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_DISCUSSION_STAGING:
        from_secret: DOCKER_REPO_DISCUSSION_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_DISCUSSION_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_DISCUSSION_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-discussion

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_DISCUSSION
      tags: latest
      dockerfile: discussion/Dockerfile
      context: discussion
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_CALENDAR:
        from_secret: DOCKER_REPO_DISCUSSION
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_DISCUSSION, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_DISCUSSION
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push
---
kind: pipeline
type: docker
name: feature-payment

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd payment
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-payment

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_PAYMENT_STAGING
      tags: latest
      dockerfile: payment/Dockerfile
      context: payment
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_PAYMENT_STAGING:
        from_secret: DOCKER_REPO_PAYMENT_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_PAYMENT_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_PAYMENT_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-payment

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_CHAT
      tags: latest
      dockerfile: payment/Dockerfile
      context: payment
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_PAYMENT:
        from_secret: DOCKER_REPO_PAYMENT
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_PAYMENT, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_PAYMENT
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push
---
kind: pipeline
type: docker
name: feature-auth

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd auth
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request
---
kind: pipeline
type: docker
name: staging-auth

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_AUTH_STAGING
      tags: latest
      dockerfile: auth/Dockerfile
      context: auth
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_AUTH_STAGING:
        from_secret: DOCKER_REPO_AUTH_STAGING
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_AUTH_STAGING, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_AUTH_STAGING
        - cd $REPO_DIR
        - git checkout master
        - git pull
        - docker-compose -f docker-compose-staging.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - master
    - main
  event:
    - push
---
kind: pipeline
type: docker
name: prod-auth

steps:
  - name: Build Docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo:
        from_secret: DOCKER_REPO_AUTH
      tags: latest
      dockerfile: auth/Dockerfile
      context: auth
  - name: Deploy
    image: appleboy/drone-ssh
    environment:
      DOCKER_REPO_AUTH:
        from_secret: DOCKER_REPO_AUTH
      REPO_DIR:
        from_secret: REPO_DIR
      ENV_FILE_PATH:
        from_secret: ENV_FILE_PATH
    settings:
      host:
        from_secret: AWS_SSH_HOST
      port:
        from_secret: AWS_SSH_PORT
      username:
        from_secret: AWS_SSH_USERNAME
      key:
        from_secret: AWS_SSH_KEY
      envs: [DOCKER_REPO_AUTH, REPO_DIR, ENV_FILE_PATH]
      script:
        - docker pull $DOCKER_REPO_AUTH
        - cd $REPO_DIR
        - git checkout production
        - git pull
        - docker-compose -f docker-compose-prod.yml --env-file $ENV_FILE_PATH  up -d
trigger:
  branch:
    - production
  event:
    - push