kind: pipeline
type: docker
name: feature-calendar

steps:
  - name: Run unit tests
    image: golang:1.16
    commands:
      - cd calendar
      - go mod download
      - go test ./...
trigger:
  branch:
    - master
    - main
  event:
    - pull_request