export const ACTION_TYPES = {
    CREATE_POST: 'CREATE_POST',
    CREATE_TOPIC: 'CREATE_TOPIC',
    GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
    GET_ALL_TOPIC_SUCCESS: 'GET_ALL_TOPIC_SUCCESS',
    GET_ALL_POSTS_FAILED: 'GET_ALL_POSTS_FAILED',
    GET_ALL_TOPIC_FAILED: 'GET_ALL_TOPIC_FAILED',
    GET_UPDATE_ALL_POSTS_SUCCESS: 'GET_UPDATE_ALL_POSTS_SUCCESS',
    GET_UPDATE_ALL_TOPIC_SUCCESS: 'GET_UPDATE_ALL_TOPIC_SUCCESS',
    CLOST_MODAL: 'CLOSE_MODAL'
};