// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dep

import (
	"database/sql"
	"github.com/yijia-cc/grouplive/calendar/auth"
	"github.com/yijia-cc/grouplive/calendar/config"
	"github.com/yijia-cc/grouplive/calendar/db/dao"
	"github.com/yijia-cc/grouplive/calendar/gql"
	"github.com/yijia-cc/grouplive/calendar/obs"
	"github.com/yijia-cc/grouplive/calendar/tx"
	"net/http"
)

// Injectors from wire.go:

func InitGraphQLServer(cfg config.Config, logger obs.Logger, db *sql.DB) (*http.ServeMux, error) {
	groupLiveAuthClient, err := newGroupLiveAuthClient(cfg)
	if err != nil {
		return nil, err
	}
	safeTransactionFactory := tx.NewSafeTransactionFactory(db)
	amenitySQL := dao.NewAmenitySQL(db)
	amenityTypeSQL := dao.NewAmenityTypeSQL(db)
	timeSlotSQL := dao.NewTimeSlotSQL(db)
	reservationSQL := dao.NewReservationSQL(db)
	weekSQL := dao.NewWeekSQL(db)
	serveMux := gql.NewServer(cfg, logger, groupLiveAuthClient, groupLiveAuthClient, groupLiveAuthClient, safeTransactionFactory, amenitySQL, amenityTypeSQL, timeSlotSQL, reservationSQL, weekSQL)
	return serveMux, nil
}

// wire.go:

func newGroupLiveAuthClient(cfg config.Config) (auth.GroupLiveAuthClient, error) {
	return auth.NewGroupLiveAuthClient(cfg.AuthGRPCEndpoint)
}
