// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package dep

import (
	"database/sql"
	"net/http"

	"github.com/yijia-cc/grouplive/auth/db/dao"
	"github.com/yijia-cc/grouplive/auth/routing"
	"github.com/yijia-cc/grouplive/auth/tm"
	"github.com/yijia-cc/grouplive/auth/tx"
)

// Injectors from wire.go:

func InitRoutingServer(jwtSigningKey JWTSigningKey, caesarCipherOffset CaesarCipherOffset, sqlDB *sql.DB) *http.ServeMux {
	localTimer := tm.NewLocalTimer()
	safeTransactionFactory := tx.NewSafeTransactionFactory(sqlDB)
	userSQL := dao.NewUserSQL(sqlDB)
	serveMux := newRoutingServer(localTimer, safeTransactionFactory, userSQL, jwtSigningKey, caesarCipherOffset)
	return serveMux
}

// wire.go:

type JWTSigningKey string

type CaesarCipherOffset int

func newRoutingServer(timer tm.Timer, txFactory tx.TransactionFactory, userDao dao.User, jwtSigningKey JWTSigningKey, caesarCipherOffset CaesarCipherOffset) *http.ServeMux {
	return routing.NewServer(timer, txFactory, userDao, string(jwtSigningKey), int(caesarCipherOffset))
}
